// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZX1WIBjMGObiqPR0OtFsTz-uDqTG2-_U',
    appId: '1:533432210019:web:7cb09b07c648374ab85e56',
    messagingSenderId: '533432210019',
    projectId: 'ecommerceapp-11eb2',
    authDomain: 'ecommerceapp-11eb2.firebaseapp.com',
    storageBucket: 'ecommerceapp-11eb2.appspot.com',
    measurementId: 'G-6N5ENPT7WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAO5BeGXDXai-UBbt4QEjQPKRS1HdenPg',
    appId: '1:533432210019:android:d39b3526b65e0095b85e56',
    messagingSenderId: '533432210019',
    projectId: 'ecommerceapp-11eb2',
    storageBucket: 'ecommerceapp-11eb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMKamF7BGEOR5rqeIR4-rX9TvTlv1qZlY',
    appId: '1:533432210019:ios:3df0b1c8c5c8d82fb85e56',
    messagingSenderId: '533432210019',
    projectId: 'ecommerceapp-11eb2',
    storageBucket: 'ecommerceapp-11eb2.appspot.com',
    iosClientId: '533432210019-2ldridros88vsejd3gg7u6c4d949jiup.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMKamF7BGEOR5rqeIR4-rX9TvTlv1qZlY',
    appId: '1:533432210019:ios:3df0b1c8c5c8d82fb85e56',
    messagingSenderId: '533432210019',
    projectId: 'ecommerceapp-11eb2',
    storageBucket: 'ecommerceapp-11eb2.appspot.com',
    iosClientId: '533432210019-2ldridros88vsejd3gg7u6c4d949jiup.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
